import { type NextPage } from "next";
import Head from "next/head";
import { signIn, signOut, useSession } from "next-auth/react";
import { api } from "~/utils/api";
import { useRouter } from "next/router";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Ultimate Rock Paper Scissors</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <h1 className="flex gap-7 font-mono text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Ultimate
            <p>
              <i className="fa-solid fa-gem text-pink-500"></i>
              <i className="fa-solid fa-toilet-paper text-cyan-500"></i>
              <i className="fa-solid fa-scissors text-green-500"></i>
            </p>
          </h1>

          <div className="flex flex-col items-center gap-2">
            <AuthShowcase />
          </div>
        </div>
      </main>
    </>
  );
};

export default Home;

const AuthShowcase: React.FC = () => {
  const { data: sessionData } = useSession();
  const router = useRouter();
  const { data: secretMessage } = api.auth.getSecretMessage.useQuery(
    undefined, // no input
    { enabled: sessionData?.user !== undefined }
  );

  if (sessionData?.user !== undefined) {
    router
      .push("lobby")
      .then()
      .catch((e) => console.error(e));
  }

  return (
    <div className="flex flex-col items-center justify-center gap-4">
      <button
        className="rounded-full bg-black px-10 py-3 text-3xl font-semibold text-white no-underline transition-all duration-200 ease-in-out hover:bg-white hover:text-black"
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Get started"}
      </button>
    </div>
  );
};


export const config = {
    runtime:"experimental-edge",
}
